# MediaMTX Configuration for WebRTC Dashboard
# Configuration for MediaMTX latest version

# Log level
logLevel: info
logDestinations: [stdout]

# Global timeouts - very long to prevent disconnects during long streams
readTimeout: 3600s
readBufferCount: 4096

# API Server (no authentication for development)
api: yes
apiAddress: :9997

# RTSP Server
rtsp: yes
protocols: [tcp]
rtspAddress: :8554

# WebRTC Server
webrtc: yes
webrtcAddress: :8891
webrtcICEServers2:
  - url: stun:stun.l.google.com:19302
# Use host mode - advertise localhost for browser connections
webrtcICEHostNAT1To1IPs: [127.0.0.1, 192.168.179.48]
webrtcAdditionalHosts: [localhost, host.docker.internal, 127.0.0.1, 192.168.179.48]

# Disable other protocols
rtmp: no
hls: no
srt: no

# Authentication - disabled for development
authMethod: internal
authInternalUsers:
  - user: any
    pass:
    ips: []
    permissions:
      - action: publish
      - action: read
      - action: playback
      - action: api
      - action: metrics
      - action: pprof

# Paths configuration
paths:
  all: